project:
  type: website
  output-dir: docs ##This is where we are hosting all of our supporting documents

website:
  title: "Dominic Vincent Schenone"
  site-url: https://dominicschenone.com
  navbar:
    left:
      - href: index.qmd ##This Hyphens, whatever is in Index.qmd ()
        text: Home
      - href: resume.qmd
        text: Resume
      - href: Projects.qmd
        text: Projects
      - href: Tennis.qmd
        text: Tennis Dashboard



format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute: 
  freeze: auto







